/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Controlador.JugadorControlador;
import Modelo.JugadorModelo;
import Objetos.Jugador;
import Vista.CuadroVista;
import Vista.JugadorVista;
import java.awt.GridLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author santi
 */
public class frmConfiguracionTablero extends javax.swing.JFrame {

    private JugadorControlador jCon;
    /**
     * Creates new form frmConfiguracionTablero
     */
    public frmConfiguracionTablero() {
        initComponents();
        inicializarControladores();
    }

    public void inicializarControladores(){
    
        this.jCon = new JugadorControlador();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOpciones = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        btnAñadirUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Añadir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(10, 10, 30, 10));

        btnAñadirUser.setText("user");
        btnAñadirUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOpcionesLayout = new javax.swing.GroupLayout(pnlOpciones);
        pnlOpciones.setLayout(pnlOpcionesLayout);
        pnlOpcionesLayout.setHorizontalGroup(
            pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcionesLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addGap(29, 29, 29)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnAñadirUser)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        pnlOpcionesLayout.setVerticalGroup(
            pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcionesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAñadirUser))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlOpciones, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        pnlJugadorConfiguracion panel = new pnlJugadorConfiguracion();
       

        int result = JOptionPane.showConfirmDialog(
                null,
                panel,
                "Configurar Jugador",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            
            Jugador jugador = panel.getJugador();
            JugadorModelo jMod = new JugadorModelo();
            jMod.agregarJugador(jugador);

            JugadorVista jVista = new JugadorVista(jugador);
            
            jCon.setModelo(jMod);
            jCon.agregarVista(jVista);
            
        }
        
//        pnlJuego.removeAll();
//
//        int cant = 100;
//
//        if((int)jSpinner1.getValue() == 10){
//            pnlJuego.setLayout(new GridLayout(10, 10));
//
//        }
//        if((int)jSpinner1.getValue() == 20){
//            pnlJuego.setLayout(new GridLayout(20, 20));
//            cant = 400;
//
//        }
//
//        if((int)jSpinner1.getValue() == 30){
//            pnlJuego.setLayout(new GridLayout(30, 30));
//            cant = 400;
//            cant = 900;
//
//        }
//        for(int i = 1; i <= cant; i++){
//
//            CuadroVista cuadro = new CuadroVista(i);
//            pnlJuego.add(cuadro);
//
//        }
//
//        pnlPrincipal.revalidate();
//        pnlPrincipal.repaint();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAñadirUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirUserActionPerformed
        // TODO add your handling code here:

        //        pnlJugador j1 = new pnlJugador();
        //        pnlJugador j2 = new pnlJugador();
        //        pnlJugador j3 = new pnlJugador();
        //        pnlJugador j4 = new pnlJugador();
        //
        //        pnlJugadores.add(j1);
        //        pnlJugadores.add(j2);
        //        pnlJugadores.add(j3);
        //        pnlJugadores.add(j4);
        //
        //        System.out.println("no entiendo");
        //
        //        pnlJugadores.revalidate();
        //        pnlJugadores.repaint();
    }//GEN-LAST:event_btnAñadirUserActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadirUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JPanel pnlOpciones;
    // End of variables declaration//GEN-END:variables
}
