/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.timbiricheatt;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;


/**
 *
 * @author santi
 */
public class Cuadro extends javax.swing.JPanel {

    public int num;
    public CuadrosListener listener;
    public boolean der = false;
    public boolean izq = false;
    public boolean arriba = false;
    public boolean abajo = false;
    public Color color;
    ImageIcon iconoDefault = new ImageIcon(getClass().getResource("/Cuadros/Cuadro.png"));
    ImageIcon iconoHover = new ImageIcon(getClass().getResource("/Cuadros/CuadroHover.png"));
    
    /**
     * Creates new form Cuadros
     */
    public Cuadro(int num) {

        this.num = num;
        initComponents();
        
       

    }
    
    public Cuadro(CuadrosListener listener, int num) {

        this.listener = listener;
        this.num = num;
        initComponents();

    }

    private void renderizarCuadro(ImageIcon icono){
        
        Image overlay = icono.getImage();
        super.getGraphics().drawImage(overlay, 0, 0, getWidth(), getHeight(), this);
        
        if(der){
       
            super.getGraphics().setColor(color);
            super.getGraphics().drawLine(getWidth() - 1, 0, getWidth() - 1, getHeight());
        
        }
            
        if(izq){
       
            super.getGraphics().setColor(color);
            super.getGraphics().drawLine(0, 0, 0, getHeight());
        
        }
            
        if(abajo){
            
            super.getGraphics().setColor(color);
            super.getGraphics().drawLine(0, getHeight()-1, getWidth(), getHeight()-1);
        
        }
            
        if(arriba){
       
            super.getGraphics().setColor(color);
            super.getGraphics().drawLine(0, 0, getWidth(), 0);
        
        }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIzqSup = new javax.swing.JLabel();

        btnIzqSup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIzqSupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIzqSupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIzqSupMouseExited(evt);
            }
        });
        btnIzqSup.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                btnIzqSupComponentResized(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnIzqSup, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnIzqSup, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public int getNum() {
        return num;
    }

    public void setNum(int num) {
        this.num = num;
    }

    public CuadrosListener getListener() {
        return listener;
    }

    public void setListener(CuadrosListener listener) {
        this.listener = listener;
    }
    
    
    private void btnIzqSupComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnIzqSupComponentResized

        renderizarCuadro(iconoDefault);

    }//GEN-LAST:event_btnIzqSupComponentResized

    private void btnIzqSupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIzqSupMouseEntered
        // TODO add your handling code here:
      
        renderizarCuadro(iconoHover);
    }//GEN-LAST:event_btnIzqSupMouseEntered

    private void btnIzqSupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIzqSupMouseClicked
        // TODO add your handling code here:
        int x = evt.getX();
        int y = evt.getY();
        int w = btnIzqSup.getWidth();
        int h = btnIzqSup.getHeight();
        
        int distLeft = x;
        int distRight = w - x;
        int distTop = y;
        int distBottom = h - y;

        int min = Math.min(Math.min(distLeft, distRight), Math.min(distTop, distBottom));

        String donde = "valioverga";
        if (min == distLeft) {
            donde = "izq";
            this.izq = true;
        } else if (min == distRight) {
            donde = "der";
            this.der = true;
        } else if (min == distTop) {
            donde = "arriba";
            this.arriba = true;
        } else {
            donde = "abajo";
            this.abajo = true;
        }
        System.out.println("Me picaron en " + donde + ", soy = " + num);
    }//GEN-LAST:event_btnIzqSupMouseClicked

    private void btnIzqSupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIzqSupMouseExited
        
        renderizarCuadro(iconoDefault);
    }//GEN-LAST:event_btnIzqSupMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnIzqSup;
    // End of variables declaration//GEN-END:variables
}
