/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.timbiricheatt;

/**
 *
 * @author santi
 */
public class pnlJugador extends javax.swing.JPanel {

    /**
     * Creates new form pnlJugador
     */
    public pnlJugador() {
        initComponents();
        lblAvatar.setVisible(false);
        lblNombre.setVisible(false);
        pnlColor.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrear = new javax.swing.JButton();
        lblAvatar = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        pnlColor = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrear.setText("Crear Jugador");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        lblAvatar.setText("jLabel1");
        add(lblAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        lblNombre.setText("jLabel1");
        add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        javax.swing.GroupLayout pnlColorLayout = new javax.swing.GroupLayout(pnlColor);
        pnlColor.setLayout(pnlColorLayout);
        pnlColorLayout.setHorizontalGroup(
            pnlColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnlColorLayout.setVerticalGroup(
            pnlColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        add(pnlColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        frmJugadorConfiguracion frm = new frmJugadorConfiguracion();
        
        frm.setVisible(true);
    }//GEN-LAST:event_btnCrearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel pnlColor;
    // End of variables declaration//GEN-END:variables
}
